class RAGOpsError(Exception):
    """Base exception for all RAGOps errors."""
    
class TenantNotFoundError(RAGOpsError): ...
class InvalidCredentials(RAGOpsError): ...
class DocumentNotFoundError(RAGOpsError): ...
class EmbeddingError(RAGOpsError): ...
class RetrievalError(RAGOpsError): ...
class GenerationError(RAGOpsError): ...
class QuotaExceededError(RAGOpsError): ...
class VectorStoreError(RAGOpsError): ...
class UnsupportedFormatError(RAGOpsError): ...